routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\ImagesController::class, 'index'])->middleware('auth', 'language');

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function (){
    Route::resource('users', \App\Http\Controllers\Admin\UsersController::class);
    Route::resource('images', \App\Http\Controllers\Admin\ImagesController::class);
    Route::resource('comments', \App\Http\Controllers\Admin\CommentsController::class)->except(['create', 'store', 'edit', 'update']);
});

Route::prefix('client')->name('client')
    ->resource('images', \App\Http\Controllers\ImagesController::class)->except(['edit', 'update'])->middleware(['auth', 'language']);
Route::prefix('client')->name('client')
    ->resource('images.comments', \App\Http\Controllers\CommentsController::class)->only(['store'])->middleware(['auth', 'language']);
Route::prefix('client')->name('client')
    ->resource('users', \App\Http\Controllers\UsersController::class)->only(['show', 'edit', 'update'])->middleware(['auth', 'language']);

Route::get('language/{locale}', [\App\Http\Controllers\LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')->where('locale', 'en|ru');




Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'image', 'user_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/Admin/ImagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ImageRequest;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('viewAny', Auth::user());
        $images = Image::orderBy('id', 'desc')->paginate(9);
        return view('admin.images.index', compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('viewAny', Auth::user());
        return view('admin.images.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ImageRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(ImageRequest $request)
    {
        $image = new Image($request->all());
        $image->user()->associate($request->user());
        if ($request->hasFile('image')) {
            $image->image = $request->file('image')->store('images', 'public');
        }
        $image->save();
        $this->authorize('viewAny', Auth::user());
        return redirect()->route('admin.images.index')->with('status', 'Image created!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Image $image
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Image $image)
    {
        $this->authorize('viewAny', Auth::user());
        $comments = $image->comments->sortByDesc('id');
        return view('admin.images.show', compact('image', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Image $image
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Image $image)
    {
        $this->authorize('viewAny', Auth::user());
        return view('admin.images.edit', compact('image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ImageRequest $request
     * @param \App\Models\Image $image
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(ImageRequest $request, Image $image)
    {
        $data = $request->all();
        if ($request->hasFile('image')){
            $path = $request->file('image')->store('images', 'public');
            $data['image'] = $path;
        }
        $image->user()->associate($request->user());
        $image->update($data);
        $this->authorize('viewAny', Auth::user());
        return redirect()->route('admin.images.index')->with('status', 'Image updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Image $image
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Image $image)
    {
        $this->authorize('viewAny', Auth::user());
        $image->delete();
        return redirect()->back()->with('status', 'Image deleted!');
    }
}

app/Http/Controllers/Api/ImagesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ImageResource;
use App\Models\Image;
use Illuminate\Http\Request;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection|\Illuminate\Http\Response
     */
    public function index()
    {
        $images = Image::all();
        return ImageResource::collection($images);
    }
}

app/Http/Controllers/ImagesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ImageRequest;
use App\Models\Image;
use Illuminate\Http\Request;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $images = Image::orderBy('id', 'desc')->paginate(9);
        return view('client.images.index', compact('images'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.images.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ImageRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(ImageRequest $request)
    {
        $image = new Image($request->all());
        $image->user()->associate($request->user());
        if ($request->hasFile('image')) {
            $image->image = $request->file('image')->store('images', 'public');
        }
        $image->save();
        $this->authorize('update', $image);
        return redirect()->route('client.images.index')->with('status', trans('messages.image_created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Image  $image
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(Image $image)
    {
        $comments = $image->comments->sortByDesc('id');
        return view('client.images.show', compact('image', 'comments'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Image $image
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Image $image)
    {
        $this->authorize('forceDelete', $image);
        $image->delete();
        return redirect()->back()->with('status', trans('messages.image_deleted'));
    }
}

resources/views/client/images/create.blade.php
@extends('layouts.client')

@section('content')

    <form enctype="multipart/form-data" action="{{route('client.images.store')}}" method="post">
        @csrf

        <div class="row mb-3">
            <label for="name" class="col-form-label">@lang('messages.name')</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="name" name="name">
            </div>
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="row mb-3">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="image" name="image">
                <label class="custom-file-label" for="image">@lang('messages.choose_image')</label>
            </div>
            @error('image')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <br>
        <button type="submit" class="btn btn-primary">@lang('messages.create_image')</button>
    </form>

@endsection

resources/views/client/images/index.blade.php
@extends('layouts.client')

@section('content')

    <h1>@lang('messages.all_images'):</h1>

    @if($images->count()>0)

        <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach($images as $image)
                <div class="col mt-2">
                    <div class="card">
                        <img src="{{asset('/storage/' . $image->image)}}" class="card-img-top" alt="{{asset('/storage/' . $image->image)}}">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{{route('client.images.show', ['image' => $image])}}">{{$image->name}}</a>
                            </h5>
                            <p class="card-text">@lang('messages.by'):
                                <a href="{{route('client.users.show', ['user' => $image->user])}}">{{$image->user->name}}</a>
                            </p>
                        </div>
                    </div>
                </div>
        @endforeach
        </div>

    @else
    <p>@lang('messages.no_images')</p>

    @endif

    <div class="row justify-content-md-center p-5">

        <div class="col-md-auto">

            {{ $images->links('pagination::bootstrap-4') }}

        </div>

    </div>

@endsection

resources/views/client/images/show.blade.php
@extends('layouts.client')

@section('content')

    <h1>{{$image->name}}</h1>
    <br>

    <img style="max-height: 1000px; max-width: 1000px" src="{{asset('/storage/'. $image->image)}}" alt="{{asset('/storage/'. $image->image)}}">

    <br>
    <p>@lang('messages.average_score'): {{round($image->comments->pluck('score')->avg(), 2)}}</p>

    <h3>@lang('messages.comments'): </h3>
    <br>

    @if(Auth::check())
    <p>
        <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">@lang('messages.create_comment')</a>
    </p>
    <div class="row">
        <div class="col">
            <div class="collapse multi-collapse" id="multiCollapseExample1">
                <div class="card card-body">
                    <form action="{{route('client.images.comments.store', ['image' => $image])}}" id="create-comment" method="post">
                        @csrf
                        <input type="hidden" id="image_id" value="{{$image->id}}">

                        <div class="form-group">
                            <label for="score">@lang('messages.your_score')</label>
                            <input min="1" max="5" step="0.5" type="number" name="score" id="score">
                        </div>
                        <div class="form-group">
                            <label for="body">@lang('messages.comment')</label>
                            <textarea name="body" class="form-control" id="body" rows="3" required></textarea>
                        </div>
                        <button id="create-comment-btn" type="submit" class="btn btn-outline-success">@lang('messages.add_new_comment')
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @endif

    <br>

    <div class="all-comments">
        @foreach($comments as $comment)

            <div id="comment-{{$comment->id}}" class="border mb-1 p-1">
                <h5>{{$comment->user->name}} score: {{$comment->score}}</h5>
                <p>{{$comment->body}}</p>
            </div>

        @endforeach
    </div>

@endsection